name: pyowp

channels:
- conda-forge
- menpo
- defaults

dependencies:
  - python>=3.9
  - numpy>=1.23.5
  - matplotlib>=3.6.2
  - seaborn>=0.11.2
  - pandas>=1.5.2
  - jupyterlab>=3.5.1
  - autopep8>=2.0.0
  - pip>=22.3.1
  - nbstripout>=0.6.1
  - requests>=2.26.0
  - geopandas>=0.11.0
  - rasterio>=1.2.10
  - pyresample
  - cartopy
  - pyhdf
  - gdal
  - h5py
  - pygrib
  - scikit-image
  - scikit-learn
  - pyproj
  - pvlib-python
  - plotly
  - pyserial
  - pip
  - openpyxl
  - folium
  - pip:
    - kaleido